//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DB3
{
    using System;
    using System.Collections.Generic;
    
    public partial class Salary
    {
        public int Salary_ID { get; set; }
        public Nullable<int> Amount { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<int> Staff_Id { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
    
        public virtual Staff Staff { get; set; }
    }
}
