//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DB3
{
    using System;
    using System.Collections.Generic;
    
    public partial class Stock
    {
        public int Stock_Id { get; set; }
        public int Quantity { get; set; }
        public Nullable<int> Medicine_Id { get; set; }
    
        public virtual Medicine Medicine { get; set; }
    }
}
